env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars: warn
  no-console: off
  eqeqeq: 
    - error
    - always
  curly: error
  comma-dangle: 
    - error
    - never
  no-trailing-spaces: error
  no-multiple-empty-lines: 
    - error
    - max: 2
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
  space-before-blocks: 
    - error
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - never
  no-undef: off