version: 0.2
phases:
  install:
    commands:
      # Navigate into the directory where your AWS SAM template and other build files are located
      - cd SyncedBackend
      # Install all dependencies (including dependencies for running tests)
      - npm install
  pre_build:
    commands:
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yaml --s3-bucket synced-cicd --output-template template-export.yml
  post_build:
    commands:
      - aws cloudformation deploy --template-file template-export.yml --stack-name synced --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
artifacts:
  type: zip
  files:
    - SyncedBackend/template-export.yml
