AWSTemplateFormatVersion: '2010-09-09'
Description: Main Stack for SyncedBackend

Resources:
  LambdaCollaborativePlaylists:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'services/collaborative-playlists-service/template.yaml'
      Parameters:
        CollaborativePlaylistTableName: !GetAtt DatabaseStack.Outputs.CollaborativePlaylistTableName
        RestApiId: !Ref ApiGateway.Outputs.ApiGatewayRestApiId

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'shared/database.yaml'

  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'shared/api.yaml'