AWSTemplateFormatVersion: '2010-09-09'
Description: Main Stack for SyncedBackend

Resources:
  LambdaGetAllCollaborativePlaylists:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'src/get-all-collaborative-playlists/template.yaml'  # Adjust this path if you host it on S3 or another location
      Parameters:
        SampleTableArn: !GetAtt DatabaseStack.Outputs.SampleTableArn

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'db/template.yaml'  # Adjust this path if you host it on S3 or another location

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !GetAtt LambdaStack.Outputs.WebEndpoint
