AWSTemplateFormatVersion: '2010-09-09'
Description: Main Stack for SyncedBackend
Resources:
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/synced-cicd/9114ac7caf7a010453a794d13678f725.template
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/synced-cicd/7e442de3a97f9e50d369ca64bd0d85fe.template
      Parameters:
        CollaborativePlaylistTableName:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.CollaborativePlaylistTableName
        UsersTableName:
          Fn::GetAtt:
          - DatabaseStack
          - Outputs.UsersTableName
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/synced-cicd/5f38ec3dae77d431edbb1a4cd3f950ed.template
      Parameters:
        CognitoTriggerFunctionArn:
          Fn::GetAtt:
          - LambdaStack
          - Outputs.CognitoTriggerFunctionArn
  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-west-2.amazonaws.com/synced-cicd/d3329a8bf46d7193372cb477e00f0dc3.template
      Parameters:
        GetAllCollaborativePlaylistsFunctionArn:
          Fn::GetAtt:
          - LambdaStack
          - Outputs.GetAllCollaborativePlaylistsFunctionArn
        UserPoolId:
          Fn::GetAtt:
          - CognitoStack
          - Outputs.UserPoolId
