AWSTemplateFormatVersion: '2010-09-09'
Description: Main Stack for SyncedBackend

Resources:
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'shared/database.yaml'

  ApiGatewayStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: 'shared/api.yaml'
        Parameters: 
          GetAllCollaborativePlaylistsResourceArn: CollaborativePlaylistsStack.Outputs.GetAllCollaborativePlaylistsResourceArn

  CollaborativePlaylistsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'services/collaborative-playlists-service/template.yaml'
      Parameters:
        CollaborativePlaylistTableName: !GetAtt DatabaseStack.Outputs.CollaborativePlaylistTableName
