AWSTemplateFormatVersion: '2010-09-09'
Description: Main Stack for SyncedBackend

Resources:
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'stacks/database.yaml'

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'stacks/lambda.yaml'
      Parameters:
        PlaylistTableName: !GetAtt DatabaseStack.Outputs.PlaylistTableName
        UsersTableName: !GetAtt DatabaseStack.Outputs.UsersTableName

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'stacks/cognito.yaml'
      Parameters:
        CognitoTriggerFunctionArn: !GetAtt LambdaStack.Outputs.CognitoTriggerFunctionArn

  ApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'stacks/api.yaml'
      Parameters:
        GetCollaborativePlaylistByIdFunctionArn: !GetAtt LambdaStack.Outputs.GetCollaborativePlaylistByIdFunctionArn
        GetAllCollaborativePlaylistsFunctionArn: !GetAtt LambdaStack.Outputs.GetAllCollaborativePlaylistsFunctionArn
        CreateCollaborativePlaylistFunctionArn: !GetAtt LambdaStack.Outputs.CreateCollaborativePlaylistFunctionArn
        UserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId

      