AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a Cognito User Pool with an App Client.

Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      UserPoolName: SyncedUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          Required: true
          Mutable: false

  MyUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyUserPool
      ClientName: MyUserPoolClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  UserPoolId:
    Description: The ID of the created user pool
    Value: !Ref MyUserPool
