AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Table Stack for SyncedBackend

Resources:
  CollaborativePlaylistTable:
    Type: AWS::Serverless::SimpleTable
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  CollaborativePlaylistTableName:
    Description: "Name of the CollaborativePlaylistTable"
    Value: !Ref CollaborativePlaylistTable