AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Stack for Synced Lambda functions
Parameters:
  UsersTableName:
    Type: String
  PlaylistTableName:
    Type: String

Resources:
  GetAllCollaborativePlaylistsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/collaborative-playlists-service/
      Handler: get-all-collaborative-playlists.getAllCollaborativePlaylistsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to get all the Collaborative Playlists for a given user.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaylistTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          PLAYLISTS_TABLE: !Ref PlaylistTableName

  CreateCollaborativePlaylistFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/collaborative-playlists-service/
      Handler: create-collaborative-playlist.createCollaborativePlaylistHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to create a Collaborative Playlists.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaylistTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          PLAYLISTS_TABLE: !Ref PlaylistTableName

  CognitoTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/users-service/
      Handler: add-user.addUserHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to add new Cognito users to the Users database.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USERS_TABLE: !Ref UsersTableName

Outputs:
  GetAllCollaborativePlaylistsFunctionArn:
    Value: !GetAtt GetAllCollaborativePlaylistsFunction.Arn
  CreateCollaborativePlaylistFunctionArn:
    Value: !GetAtt CreateCollaborativePlaylistFunction.Arn
  CognitoTriggerFunctionArn:
    Value: !GetAtt CognitoTriggerFunction.Arn