AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Stack for Synced
Parameters:
  UsersTableName:
    Type: String
  PlaylistsTableName:
    Type: String
  TokensTableName:
    Type: String
  LambdaFailureTopicName:
    Type: String

Resources:
  CommonLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: synced-static-storage
        S3Key: layer.zip
      CompatibleRuntimes:
        - nodejs18.x
      Description: "Common Node.js dependencies for Lambda"

  GetCollaborativePlaylistByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/collaborative-playlists-service/   
      Handler: get-collaborative-playlist-by-id.getCollaborativePlaylistByIdHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to get all items for a given playlist ID.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the PlaylistTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaylistsTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTableName
      Environment:
        Variables:
          PLAYLISTS_TABLE: !Ref PlaylistsTableName
          USERS_TABLE: !Ref UsersTableName

  GetAllCollaborativePlaylistsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/collaborative-playlists-service/
      Handler: get-all-collaborative-playlists.getAllCollaborativePlaylistsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to get all the Collaborative Playlists for a given user.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaylistsTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          PLAYLISTS_TABLE: !Ref PlaylistsTableName

  CreateCollaborativePlaylistFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/collaborative-playlists-service/
      Handler: create-collaborative-playlist.createCollaborativePlaylistHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to create a Collaborative Playlists.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaylistsTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          PLAYLISTS_TABLE: !Ref PlaylistsTableName

  UpdateCollaborativePlaylistMetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/collaborative-playlists-service/
      Handler: update-collaborative-playlist-metadata.updateCollaborativePlaylistMetadataHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to update Collaborative Playlists metadata.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaylistsTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          PLAYLISTS_TABLE: !Ref PlaylistsTableName

  AddCollaboratorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/collaborative-playlists-service/
      Handler: add-collaborators.addCollaboratorsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to add Collaborators to Collaborative Playlists.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaylistsTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          PLAYLISTS_TABLE: !Ref PlaylistsTableName
          USERS_TABLE: !Ref UsersTableName

  DeleteCollaboratorsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/collaborative-playlists-service/
      Handler: delete-collaborators.deleteCollaboratorsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to delete from Collaborative Playlists.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaylistsTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          PLAYLISTS_TABLE: !Ref PlaylistsTableName

  CognitoTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/users-service/
      Handler: create-user.createUserHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to create new Cognito users to the Users database.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTableName
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USERS_TABLE: !Ref UsersTableName

  UpdateSpotifyDevTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../services/token-service/
      Handler: update-spotify-dev-token.updateSpotifyDevTokenHandler
      Runtime: nodejs18.x
      Layers:
        - !Ref CommonLayer
      Architectures:
          - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A function to update the Spotify Developer token in the Tokens database.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TokensTableName
        - Statement:
            - Effect: "Allow"
              Action:
              # This permission is required to access SSM Parameter Store
                - "ssm:GetParameter"
              Resource: "*"  # Restrict this to specific resources if possible
      Environment:
        Variables:
          TOKENS_TABLE: !Ref TokensTableName  
          LAMBDA_FAILURE_TOPIC: !Ref LambdaFailureTopicName

Outputs:
  GetCollaborativePlaylistByIdFunctionArn:
    Value: !GetAtt GetCollaborativePlaylistByIdFunction.Arn
  GetAllCollaborativePlaylistsFunctionArn:
    Value: !GetAtt GetAllCollaborativePlaylistsFunction.Arn
  CreateCollaborativePlaylistFunctionArn:
    Value: !GetAtt CreateCollaborativePlaylistFunction.Arn
  UpdateCollaborativePlaylistMetadataFunctionArn:
    Value: !GetAtt UpdateCollaborativePlaylistMetadataFunction.Arn
  AddCollaboratorsFunctionArn:
    Value: !GetAtt AddCollaboratorsFunction.Arn
  DeleteCollaboratorsFunctionArn:
    Value: !GetAtt DeleteCollaboratorsFunction.Arn
  CognitoTriggerFunctionArn:
    Value: !GetAtt CognitoTriggerFunction.Arn
  UpdateSpotifyDevTokenFunctionArn:
    Value: !GetAtt UpdateSpotifyDevTokenFunction.Arn
