AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Stack for Synced

Resources:
  ImageUploadBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: ['GET']
            AllowedOrigins: ['*']
            MaxAge: 3000
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImageUploadBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForImagesFolder
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${ImageUploadBucket}/images/*'

Outputs:
  BucketName:
    Value: !Ref ImageUploadBucket
  BucketArn:
    Value: !GetAtt ImageUploadBucket.Arn