AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Stack for Synced

Resources:
  ImageUploadBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: ['GET', 'PUT', 'POST', 'DELETE', 'HEAD']
            AllowedOrigins: ['*']
            MaxAge: 3000

Outputs:
  BucketArn:
    Value: !GetAtt ImageUploadBucket.Arn
