AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Function for getting all Collaborative Playlists
Parameters:
  CollaborativePlaylistTableName:
    Type: String
    Description: The name of the DynamoDB table for collaborative playlists.
    
Resources:
  GetAllCollaborativePlaylists:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-all-items.getAllCollaborativePlaylistsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from a DynamoDB table.
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: CollaborativePlaylistTable
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          SAMPLE_TABLE: CollaborativePlaylistTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET