platform :ios, '17.0'

target 'Synced' do
  use_frameworks!

  # Pods for Synced
  pod 'AWSCognito'
  pod 'AWSCognitoIdentityProvider'

  target 'SyncedUnitTest' do
    inherit! :search_paths
    # Pods for testing
    # If there are specific pods you use only in your tests, add them here.
    # For example:
    # pod 'OCMock'
  end
end
