name: Sync to GitLab Repository

on:
  push:
    branches:
      - actions-fix

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Push to GitLab
      run: |
        git config --global user.name 'Jack Hurt'
        git config --global user.email ${{ secrets.UNI_EMAIL }}
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@git.cs.bham.ac.uk/projects-2023-24/jxh1292.git
        git push gitlab github --force
